version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"    # Porta principal para todos os servi√ßos
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,kms
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-init:/etc/localstack/init/ready.d:ro
      - localstack_data:/var/lib/localstack

  mysql:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ethereum_exchange
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: ./src/database/migrations/001_create_smart_contract_table.sql
        target: /docker-entrypoint-initdb.d/001_create_smart_contract_table.sql
        read_only: true
      - type: bind
        source: ./src/database/migrations/002_create_transactions_table.sql
        target: /docker-entrypoint-initdb.d/002_create_transactions_table.sql
        read_only: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  localstack_data: